### ISSUE TITLE
Reference ROKS documentation on ServiceId limitation

### ISSUE THREAD

**Issue by vburckhardt** [ibm-cloud-docs/secure-infrastructure-vpc#1]
In https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-known-issues - add a pointer to ROKS documentation at https://cloud.ibm.com/docs/openshift?topic=openshift-access-creds#owner_permissions to give full context

**Comment by vburckhardt** [comment]
@SirSpidey - FYA

**Comment by SirSpidey** [comment]
Done. See https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-known-issues#ki-svc-key-rhos
