### ISSUE TITLE
Doc linking to a cryptic github bug report

### ISSUE THREAD

**Issue by vburckhardt** [ibm-cloud-docs/secure-infrastructure-vpc#3]
In https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-known-issues#ki-policy-404

There is a link to that provider bug report https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4413 . Most customer using DA from Catalog / Project / UI would not understand what is in that ticket - suggest to remove the reference.

**Comment by SirSpidey** [comment]
Removed.
