### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vburckhardt** [ibm-cloud-docs/secure-infrastructure-vpc#4]
The link at https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-faqs (to https://cloud.ibm.com/docs/solution-as-code?topic=solution-as-code-what-is ) is broken.

@SirSpidey - fya

**Comment by SirSpidey** [comment]
Done. See https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-faqs#what-is-da
