### ISSUE TITLE
Public doc pointing to staging environment

### ISSUE THREAD

**Issue by vburckhardt** [ibm-cloud-docs/secure-infrastructure-vpc#5]
https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-deploy

Learn about IaC deployment with project points to test.cloud.ibm.com

**Comment by vburckhardt** [comment]
@SirSpidey - fya

**Comment by SirSpidey** [comment]
pushed to production from internal build.
